### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc2' in file Northcliff_AQI_Monitor_Gen.py on line 1103

### ISSUE THREAD

**Issue by ChrisKoh83** [roscoe81/enviro-monitor#5]
I´m getting this error if I try to run Northcliff_AQI_Monitor_Gen.py on my Raspi Zero.

```bash
File "Northcliff_AQI_Monitor_Gen.py", line 1103
SyntaxError: Non-ASCII character '\xc2' in file Northcliff_AQI_Monitor_Gen.py on line 1103, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

If I google the error message:  `SyntaxError: Non-ASCII character '\xc2' in file` I´m getting the hint to: [https://stackoverflow.com/questions/18078851/syntaxerror-of-non-ascii-character](url)
Set  # -*- coding: utf-8 -*- on top of the script.

But if I do that and run the py I`m gettin this:

```bash
File "Northcliff_AQI_Monitor_Gen.py", line 1105
    temp_string = f"{data['Temp'][1]:.0f}°C"
                                            ^
SyntaxError: invalid syntax
```

maybe this has something to do with my location settings?

```bash
pi@raspberrypi:~/enviro-monitor $ sudo raspi-config
Generating locales (this might take a while)...
  de_DE.UTF-8...
```

**Comment by ChrisKoh83** [comment]
> What happens when you run?
> 
> import sys
> print sys.getdefaultencoding()

```bash
pi@raspberrypi:~/enviro-monitor $ tail testLocation.py
#!/usr/bin/env python3

import sys
print sys.getdefaultencoding()
pi@raspberrypi:~/enviro-monitor $ python testLocation.py
ascii
pi@raspberrypi:~/enviro-monitor $
```

**Comment by ChrisKoh83** [comment]
> Another thought ...
> 
> Have you tried this at the top of your script?
> `# -*- coding: de_DE.UTF-8 -*-`

```bash
python Northcliff_AQI_Monitor_Gen.py
  File "Northcliff_AQI_Monitor_Gen.py", line 1
SyntaxError: encoding problem: de_DE.UTF-8
```

```bash
pi@raspberrypi:~/enviro-monitor $ head -5 Northcliff_AQI_Monitor_Gen.py
# -*- coding: de_DE.UTF-8 -*-
#!/usr/bin/env python3
#Northcliff Environment Monitor
# Requires Home Manager >=8.54 with Enviro Monitor timeout
```

**Comment by roscoe81** [comment]
Thanks for that @ChrisKoh83 

I'm far from an expert in this area but it looks like your default encoding is ASCII and that's causing the issue.
Due to formatting issues, I'm not sure what you initially tried.

Did you try this at the top of your file?

`# -*- coding: utf-8 -*-`

Other than checking that, it might be a difference with the degree symbol entry via a German keyboard. You could try replacing the degree symbol in `temp_string = f"{data['Temp'][1]:.0f}°C"` with the degree symbol from your own keyboard and if that fails, delete the degree symbol altogether.

**Comment by ChrisKoh83** [comment]
I have to thank you for your support!

I tryed the following things:

# added: `# -*- coding: utf-8 -*-`
```bash
pi@raspberrypi:~/enviro-monitor $ nano Northcliff_AQI_Monitor_Gen.py
pi@raspberrypi:~/enviro-monitor $ python Northcliff_AQI_Monitor_Gen.py
  File "Northcliff_AQI_Monitor_Gen.py", line 1111
    temp_string = f"{data['Temp'][1]:.0f}°C"
                                            ^
SyntaxError: invalid syntax
```
# changed the "°" degreed symbol
```bash
pi@raspberrypi:~/enviro-monitor $ nano Northcliff_AQI_Monitor_Gen.py
pi@raspberrypi:~/enviro-monitor $ python Northcliff_AQI_Monitor_Gen.py
  File "Northcliff_AQI_Monitor_Gen.py", line 1111
    temp_string = f"{data['Temp'][1]:.0f}°C"
                                            ^
SyntaxError: invalid syntax
```

# removed the "°" degreed symbol
``` bash
pi@raspberrypi:~/enviro-monitor $ nano Northcliff_AQI_Monitor_Gen.py
pi@raspberrypi:~/enviro-monitor $ python Northcliff_AQI_Monitor_Gen.py
  File "Northcliff_AQI_Monitor_Gen.py", line 1111
    temp_string = f"{data['Temp'][1]:.0f} C"
                                           ^
SyntaxError: invalid syntax
```

# removed the degree and the "C"
```bash
pi@raspberrypi:~/enviro-monitor $ nano Northcliff_AQI_Monitor_Gen.py
pi@raspberrypi:~/enviro-monitor $ python Northcliff_AQI_Monitor_Gen.py
  File "Northcliff_AQI_Monitor_Gen.py", line 1111
    temp_string = f"{data['Temp'][1]:.0f}"
                                         ^
SyntaxError: invalid syntax
```

I have no idea whats going on here :(

**Comment by ChrisKoh83** [comment]
python is complaining about the double qutes: 
[https://stackoverflow.com/questions/25445439/what-does-syntaxerror-missing-parentheses-in-call-to-print-mean-in-python](https://stackoverflow.com/questions/25445439/what-does-syntaxerror-missing-parentheses-in-call-to-print-mean-in-python)

so I added round bracket on every "f"  I found. Like `temp_string = f("{data['Temp'][1]:.0f} °C")`

That pushed me right to the next error...

```bash
pi@raspberrypi:~/enviro-monitor $ python Northcliff_AQI_Monitor_Gen.py
Traceback (most recent call last):
  File "Northcliff_AQI_Monitor_Gen.py", line 18, in <module>
    import requests
ImportError: No module named requests
```

**Comment by roscoe81** [comment]
Wow! Lots of issues at each step - even for those parts that are identical to the Pimoroni Examples. I'm running Python 3 and it looks like you're running Python 2.7. Have you tried running it on Python 3?

**Comment by ChrisKoh83** [comment]
python3 is a good hint!

but then:

```bash
pi@raspberrypi:~/enviro-monitor $ python3 Northcliff_AQI_Monitor_Gen.py
2020-08-24 11:14:50.690 INFO     Northcliff_Environment_Monitor.py - Pimoroni Enviro+ (and optional SGP30) sensor capture and display, plus external sensor capture and Luftdaten, mqtt and Adafruit IO Updates
#Note: you'll need to register with Luftdaten at:
#https://meine.luftdaten.info/ and enter your Raspberry Pi
#serial number that's displayed on the Enviro plus LCD along
#with the other details before the data appears on the
#Luftdaten map.

#
5.22 - Gen
Config Retrieval Failed
Traceback (most recent call last):
  File "Northcliff_AQI_Monitor_Gen.py", line 145, in <module>
    city_name, time_zone, custom_locations) = retrieve_config()
  File "Northcliff_AQI_Monitor_Gen.py", line 90, in retrieve_config
    temp_offset = parsed_config_parameters['temp_offset']
UnboundLocalError: local variable 'parsed_config_parameters' referenced before assignment
```

after that I "reordered" some lines in your script to get rid of the "referenced before assignment" error:

```python3
# Initialize display
disp.begin()

def retrieve_config():
    try:
        with open('<Your config.json file location>', 'r') as f:
            parsed_config_parameters = json.loads(f.read())
            print('Retrieved Config', parsed_config_parameters)
    except IOError:
        print('Config Retrieval Failed')

# Config Setup
  (temp_offset, altitude, enable_display, enable_adafruit_io, aio_user_name, aio_key, aio_feed_window, aio_feed_sequence,
  aio_household_prefix, aio_location_prefix, aio_package, enable_send_data_to_homemanager,
  enable_receive_data_from_homemanager, enable_indoor_outdoor_functionality, mqtt_broker_name,
  enable_luftdaten, enable_climate_and_gas_logging,  enable_particle_sensor, enable_eco2_tvoc, gas_daily_r0_calibration_hour, reset_gas_sensor_calibration,
  incoming_temp_hum_mqtt_topic, incoming_temp_hum_mqtt_sensor_name, incoming_barometer_mqtt_topic, incoming_barometer_sensor_id,
  indoor_outdoor_function, mqtt_client_name, outdoor_mqtt_topic, indoor_mqtt_topic,
  city_name, time_zone) = retrieve_config()

    temp_offset = parsed_config_parameters['temp_offset']
    altitude = parsed_config_parameters['altitude']
...
...
...
```
but now I´m stuck there:

```bash
pi@raspberrypi:~/enviro-monitor $ python3 Northcliff_AQI_Monitor_Gen.py
  File "Northcliff_AQI_Monitor_Gen.py", line 105
    temp_offset = parsed_config_parameters['temp_offset']
    ^
IndentationError: unexpected indent
```

**Comment by roscoe81** [comment]
It appears that you haven’t correctly set up your config file as per [these instructions](https://github.com/roscoe81/enviro-monitor/blob/master/Config/Config_README.md) and you haven’t updated Line 77 to reference the location of your config file.

That caused the referenced before assignment error and you didn’t need to reorder any lines of the script.

Do not re-order the script but instead, read all of the readme instructions and use the config file [here](https://github.com/roscoe81/enviro-monitor/blob/master/Config/Config_README.md) as a starting point, store it in your chosen location and reference it in Line 77.

Also, you will need to modify all other file references enclosed with `<>` to suit your setup. The script is generic and needs to be customised for a particular user’s setup.

**Comment by ChrisKoh83** [comment]
I´m sorry! I didn´t read this instructions carfully enough.

I have edited the config.json like this:

```json
{"version": "Base-5.19",
"temp_offset": 0,
"altitude": 240,
"enable_display": true,
"enable_adafruit_io": false,
"aio_user_name": "",
"aio_key": "",
"aio_feed_window": 0,
"aio_feed_sequence": 0,
"aio_household_prefix": "",
"aio_location_prefix": "",
"aio_package": "",
"enable_send_data_to_homemanager": false,
"enable_receive_data_from_homemanager": false,
"enable_indoor_outdoor_functionality": false,
"mqtt_broker_name": "",
"enable_luftdaten": false,
"enable_climate_and_gas_logging": false,
"enable_particle_sensor": false,
"enable_eco2_tvoc": false,
"gas_daily_r0_calibration_hour": 3,
"reset_gas_sensor_calibration": false,
"incoming_temp_hum_mqtt_topic": "",
"incoming_temp_hum_mqtt_sensor_name": "",
"incoming_barometer_mqtt_topic": "",
"incoming_barometer_sensor_id": 0,
"indoor_outdoor_function": "Indoor",
"mqtt_client_name": "",
"outdoor_mqtt_topic": "",
"indoor_mqtt_topic": "",
"city_name": "Stuttgart",
"time_zone": "Europe/Berlin",
"custom_locations": ["Stuttgart, Gernmany, Berlin, xx.xxxxx, x.xxxxxx"]}
```

and places the path to the config.json in Line:

![image](https://user-images.githubusercontent.com/13451391/91083820-38512880-e64b-11ea-8cf9-af63a37142b2.png)

 
```bash
pi@raspberrypi:~/enviro-monitor $ python3 Northcliff_AQI_Monitor_Gen.py
2020-08-24 20:49:18.335 INFO     Northcliff_Environment_Monitor.py - Pimoroni Enviro+ (and optional SGP30) sensor capture and display, plus external sensor capture and Luftdaten, mqtt and Adafruit IO Updates
#Note: you'll need to register with Luftdaten at:
#https://meine.luftdaten.info/ and enter your Raspberry Pi
#serial number that's displayed on the Enviro plus LCD along
#with the other details before the data appears on the
#Luftdaten map.

#
5.22 - Gen
Retrieved Config {'version': 'Base-5.19', 'temp_offset': 0, 'altitude': 240, 'enable_display': True, 'enable_adafruit_io': False, 'aio_user_name': '', 'aio_key': '', 'aio_feed_window': 0, 'aio_feed_sequence': 0, 'aio_household_prefix': '', 'aio_location_prefix': '', 'aio_package': '', 'enable_send_data_to_homemanager': False, 'enable_receive_data_from_homemanager': False, 'enable_indoor_outdoor_functionality': False, 'mqtt_broker_name': '', 'enable_luftdaten': False, 'enable_climate_and_gas_logging': False, 'enable_particle_sensor': False, 'enable_eco2_tvoc': False, 'gas_daily_r0_calibration_hour': 3, 'reset_gas_sensor_calibration': False, 'incoming_temp_hum_mqtt_topic': '', 'incoming_temp_hum_mqtt_sensor_name': '', 'incoming_barometer_mqtt_topic': '', 'incoming_barometer_sensor_id': 0, 'indoor_outdoor_function': 'Indoor', 'mqtt_client_name': '', 'outdoor_mqtt_topic': '', 'indoor_mqtt_topic': '', 'city_name': 'Stuttgart', 'time_zone': 'Europe/Berlin', 'custom_locations': ['Stuttgart, Gernmany, Berlin, xx.xxxxx, x.xxxxxxx']}
2020-08-24 20:49:19.730 INFO     Raspberry Pi serial: 00000000xxxxxxxxxxx
2020-08-24 20:49:19.760 INFO     Wi-Fi: connected

Startup R0. Red R0: 14000.0 Oxi R0: 1196.0 NH3 R0: 1678.0
No Mender Software Version Available. Using Default
No Mender Config Version Available. Using Default
No Persistent Data Log Available. Using Defaults
Internal Temp/Hum Sensor
Internal Barometer
Raw Bar: 966.3 Comp Bar: 994.0
Reading Raw Gas sensors before warmup completed
Red Rs: 10523.0 Oxi Rs: 722.0 NH3 Rs: 984.0
Luftdaten Values {'temperature': '16.63', 'humidity': '100.00', 'pressure': '96634.18'}
mqtt Values {'Gas Calibrated': False, 'Bar': [994.0, '0'], 'Hum': [100, '3'], 'Forecast': {'Valid': False, '3 Hour Change': 0, 'Forecast': 'Insufficient Data'}, 'Temp': 16.6, 'Min Temp': None, 'Max Temp': None, 'Red': 6.24, 'Oxi': 0.09, 'NH3': 1.8, 'Lux': 185.5}
Waiting for next capture cycle
Barometer Logged. Waiting for next capture cycle
Traceback (most recent call last):
  File "Northcliff_AQI_Monitor_Gen.py", line 1718, in <module>
    enable_adafruit_io, aio_user_name, aio_household_prefix, enable_eco2_tvoc)
  File "Northcliff_AQI_Monitor_Gen.py", line 746, in display_results
    air_quality_data_no_gas, icon_air_quality_levels, gas_sensors_warm)
  File "Northcliff_AQI_Monitor_Gen.py", line 1113, in display_icon_weather_aqi
    temp_string = f("{data['Temp'][1]:.0f} °C")
TypeError: '_io.TextIOWrapper' object is not callable
```
